"use client";

import Link from "next/link";
import { useAuth } from "@clerk/nextjs";

const STEPS = [
  {
    step: "01",
    icon: "📄",
    title: "Upload your CV",
    desc: "Upload a PDF or DOCX file from your dashboard. Our system parses the text, splits it into chunks, and embeds it into a vector database — so every question asked is grounded in your actual experience.",
    detail: [
      "Supports PDF and DOCX formats",
      "Content is chunked and embedded via Mistral AI",
      "Stored securely per user — only you can access it",
    ],
  },
  {
    step: "02",
    icon: "🎯",
    title: "Pick your session",
    desc: "Before starting, choose how many questions you want — 3, 5, 7, or 10. The AI then generates questions by reading your embedded CV content, so every session is unique to your background.",
    detail: [
      "Choose 3, 5, 7, or 10 questions",
      "Questions generated by Groq LLaMA 3.3 70B",
      "No two sessions are the same",
    ],
  },
  {
    step: "03",
    icon: "🔊",
    title: "Listen to the question",
    desc: "Each question is read aloud using Groq's text-to-speech engine. You hear it spoken naturally — just like a real interviewer would ask it — giving you time to think before answering.",
    detail: [
      "Powered by Groq Orpheus TTS",
      "Natural voice delivery",
      "Question also shown as text on screen",
    ],
  },
  {
    step: "04",
    icon: "🎙️",
    title: "Answer by voice",
    desc: "Click 'Done Answering' when you're ready to stop. Your audio is sent to Groq Whisper for transcription. The transcript is shown on screen so you can see exactly what was recorded.",
    detail: [
      "Transcribed by Groq Whisper large-v3",
      "Transcript shown in real time",
      "Your answer is saved to the session",
    ],
  },
  {
    step: "05",
    icon: "⚡",
    title: "Get instant AI feedback",
    desc: "Once all questions are answered, the AI evaluates your entire session — comparing your answers against your CV content. You receive a score out of 100, strengths, areas to improve, and specific CV feedback.",
    detail: [
      "Overall score out of 100",
      "Strengths and improvement areas",
      "Detailed CV feedback from the AI",
    ],
  },
  {
    step: "06",
    icon: "📋",
    title: "Review your history",
    desc: "Every session is saved. Visit the History page to review all past interviews — see the questions asked, your transcribed answers, your score, and the full feedback from the AI.",
    detail: [
      "All sessions saved permanently",
      "Full Q&A transcript per session",
      "Feedback and score for every completed interview",
    ],
  },
];

const TECH = [
  { name: "Next.js", desc: "Frontend framework", icon: "▲" },
  { name: "FastAPI", desc: "Backend API", icon: "⚡" },
  { name: "Groq", desc: "LLM + TTS + STT", icon: "🧠" },
  { name: "Mistral AI", desc: "CV embeddings", icon: "🔷" },
  { name: "ChromaDB", desc: "Vector database", icon: "🟣" },
  { name: "PostgreSQL", desc: "Sessions & feedback store", icon: "🐘" },
  { name: "Clerk", desc: "Authentication", icon: "🔐" },
  { name: "WebSockets", desc: "Real-time communication", icon: "🔌" },
];

export default function PracticePage() {
  const { isSignedIn } = useAuth();

  return (
    <div className="practice-page">
      <div className="practice-hero">
        <div className="orb orb-1" style={{ opacity: 0.5 }} />
        <div className="orb orb-2" style={{ opacity: 0.4 }} />
        <span className="section-label">How it works</span>
        <h1 className="practice-hero__title">
          From CV to feedback
          <br />
          <span style={{ color: "var(--accent)" }}>in under 5 minutes</span>
        </h1>
        <p className="practice-hero__sub">
          InterviewAI turns your CV into a personalised voice interview —
          powered by real AI models, not templates.
        </p>
      </div>

      <div className="practice-steps">
        {STEPS.map((s, i) => (
          <div className="practice-step" key={s.step}>
            <div className="practice-step__left">
              <div className="practice-step__num">{s.step}</div>
              {i < STEPS.length - 1 && <div className="practice-step__line" />}
            </div>

            <div className="practice-step__content">
              <div className="practice-step__icon">{s.icon}</div>
              <h2 className="practice-step__title">{s.title}</h2>
              <p className="practice-step__desc">{s.desc}</p>
              <ul className="practice-step__detail">
                {s.detail.map((d, j) => (
                  <li key={j}>
                    <span className="detail-check">✓</span>
                    {d}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        ))}
      </div>

      <div className="tech-section">
        <span className="section-label">Under the hood</span>
        <h2 className="section-title">Built with real AI infrastructure</h2>
        <p className="section-sub">
          No toy demos. Every part of the pipeline uses production-grade models
          and services.
        </p>
        <div className="tech-grid">
          {TECH.map((t) => (
            <div className="tech-card" key={t.name}>
              <span className="tech-card__icon">{t.icon}</span>
              <span className="tech-card__name">{t.name}</span>
              <span className="tech-card__desc">{t.desc}</span>
            </div>
          ))}
        </div>
      </div>

      <div className="practice-cta">
        <h2>Ready to try it?</h2>
        <p>Upload your CV and run your first interview in under 2 minutes.</p>
        <div
          className="hero-ctas"
          style={{ justifyContent: "center", marginBottom: 0 }}
        >
          {isSignedIn ? (
            <Link href="/dashboard" className="cta-primary">
              Go to Dashboard →
            </Link>
          ) : (
            <>
              <Link href="/sign-up" className="cta-primary">
                Start for free →
              </Link>
              <Link href="/sign-in" className="cta-secondary">
                Sign in
              </Link>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
